[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SHARP_DIST_BASE_URL = "https://github.com/lovell/sharp-libvips/releases/download/v8.15.1"
